export default {
  LOADING_CONVERSATIONS: "LOADING_CONVERSATIONS",
  LOADING_MESSAGES: "LOADING_MESSAGES",
  FETCH_CONVERSATIONS: "FETCH_CONVERSATIONS",
  FETCH_MESSAGES: "FETCH_MESSAGES",
  CONVERSATIONS_ERROR: "CONVERSATIONS_ERROR",
  MESSAGES_ERROR: "MESSAGES_ERROR",
  NEW_MESSAGE: "NEW_MESSAGE"
};
