export default {
  LOADING_FAVORITE: "LOADING_FAVORITE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
  ADD_FAVORITE: "ADD_FAVORITE",
  FETCH_FAVORITE: "FETCH_FAVORITE",
  FAVORITE_ERROR: "FAVORITE_ERROR"
};
